Metrics forwarder pko setup
openshift/hypershift-dataplane-metrics-forwarder pull request #3
Opened 2023-02-17 03:20 UTC by Tafhim

This PR resolves both [OSD-14716](https://issues.redhat.com/browse/OSD-14716) and [OSD-14718](https://issues.redhat.com/browse/OSD-14718). This is part of the Epic [SDE-1991](https://issues.redhat.com/browse/SDE-1991).

It adds package that is deployed on HCP Namespaces. It also add the policies that are going to be used to deploy CMO Config to hosted clusters and the package to the HCP namespaces.

2023-02-17 03:34 UTC, supreeth7 commented
Can you please add a description?

2023-02-17 03:55 UTC, supreeth7 requested changes
Overall looks good, thanks for all the hard work!
A few minor issues to be addressed.

2023-02-17 03:55 UTC, supreeth7 commented on README.md
> +# Metrics Forwarder
```suggestion
# Dataplane Metrics Forwarder
```

2023-02-17 03:55 UTC, supreeth7 commented on README.md
> +The Metrics Forwarder is a Proxy that lives in each Hosted Control Plane (HCP) Namespace in Management Clusters. The main goal of this Proxy is to let the relevant Hosted Cluster's Data Plane push me
```suggestion
The dataplane metrics forwarder is a proxy that lives in each hosted control plane (HCP) namespace in management clusters. The main goal of this proxy is to let the hosted clusters push metrics to RHOBS. This proxy exposes a route that is known to the Cluster Monitoring Operator (CMO) running in the dataplane. The CMO pushes the metrics to this route. And the proxy simply forwards this request to the OpenShift Observability Operator (OBO) running on the relevant management cluster. This way the dataplane metrics ultimately end up in RHOBS.
```

2023-02-17 03:55 UTC, supreeth7 commented on README.md
> +The proxy is deployed using ACM policy. The ACM Policy targets all Management Clusters and only HCP Namespaces in those Management Clusters. It deploys a PKO Package which deploys the resources the p
```suggestion
The proxy is deployed using ACM policy. The ACM policy targets all management clusters and only HCP namespaces in those management clusters. It deploys a PKO package which deploys the resources the proxy needs. The resources it deploys are:
```

2023-02-17 03:55 UTC, supreeth7 commented on README.md
> +Additionally, the CMO on the Data Plane is configured using another Policy that only targets Hosted Clusters.
```suggestion
Additionally, the CMO on the dataplane is configured using another policy that only targets hosted clusters.
```

2023-02-17 03:55 UTC, supreeth7 commented on README.md
> +Initially, PKO Package deploys 4 resources:
```suggestion
The proxy needs to be initialized to work properly. This phase might not be needed later if the root-ca contains certificates that are compatible with [cert-manager](https://cert-manager.io/).
Initially, PKO package deploys 4 resources:
```

2023-02-17 03:55 UTC, supreeth7 commented on README.md
> +This CronJob mianly recreates the root-ca in the HCP with names that are compatible with Cert Manager.
```suggestion
This CronJob mainly recreates the root-ca in the HCP with names that are compatible with cert-manager. 
```

2023-02-17 03:55 UTC, supreeth7 commented on dataplane-policy.yaml
> +                        # so that killswitch instructions point to the right file!
```suggestion
```
This can be removed

2023-02-17 03:55 UTC, supreeth7 commented on dataplane-policy.yaml
> +                - complianceType: musthave
```suggestion
                - complianceType: mustonlyhave
```
This is related to a bug, more details in https://issues.redhat.com/browse/OSD-15177

2023-02-17 03:55 UTC, supreeth7 commented on dataplane-policy.yaml
> +                                maxBackoff: 5s
```suggestion
                                capacity: 10000
                                maxShards: 500
                                minShards: 1
                                maxSamplesPerSend: 2000
                                batchSendDeadline: 60s
                                minBackoff: 30ms
                                maxBackoff: 30s
```

2023-02-17 03:55 UTC, supreeth7 commented on dataplane-policy.yaml
> +                              operator: Exists
```suggestion
```
We do not need this, ref: https://issues.redhat.com/browse/OSD-14556

2023-02-17 03:55 UTC, supreeth7 commented on package/manifest.yaml
> +
No new line EOF

2023-02-17 04:12 UTC, wanghaoran1988 commented on README.md
> +Additionally, the CMO on the Data Plane is configured using another Policy that only targets Hosted Clusters.
policy -> ACM policy?

2023-02-17 04:14 UTC, wanghaoran1988 commented on README.md
> +## Contact
Let's remove this part? since the channel are redhat internal slack channel.

2023-02-17 04:15 UTC, wanghaoran1988 commented on dataplane-policy.yaml
> +                        # so that killswitch instructions point to the right file!
+1

2023-02-17 04:17 UTC, wanghaoran1988 commented on dataplane-policy.yaml
> +                                insecureSkipVerify: true
Does this has to be true?

2023-02-17 04:22 UTC, wanghaoran1988 commented on package/resources.yaml.gotmpl
> +  # secretTemplate is optional. If set, these annotations and labels will be
remove the comment here?

2023-02-17 04:24 UTC, wanghaoran1988 commented on package/resources.yaml.gotmpl
> +  duration: 21600h
This is 30 month, let's make it 25960, so it's 36 month?

2023-02-17 04:25 UTC, supreeth7 commented on dataplane-policy.yaml
> +                                insecureSkipVerify: true
Had the same doubt, it is `true` in our default CMO config.

2023-02-17 04:25 UTC, wanghaoran1988 commented on package/resources.yaml.gotmpl
> +  commonName:
Let's remove this? since it's deprecated since 2000 in the comment.

2023-02-17 04:30 UTC, wanghaoran1988 commented on README.md
> +## Contact
We can ignore that now.

2023-02-17 04:30 UTC, wanghaoran1988 commented on dataplane-policy.yaml
> +                                insecureSkipVerify: true
should be, but worth a test to see whether it works or not.

2023-02-20 03:39 UTC, supreeth7 commented
/label tide/merge-method-squash

/override ci/prow/images

2023-02-20 04:04 UTC, supreeth7 commented
/lgtm
/approve

2023-02-20 06:24 UTC, supreeth7 commented
/retest

2023-02-20 06:31 UTC, supreeth7 commented
/lgtm
/approve

2023-02-20 06:36 UTC, merged