update the prometheus remote write to use apiServerInternalURI from infrastructure
openshift/hypershift-dataplane-metrics-forwarder pull request #54
Opened 2024-03-19 07:56 UTC by bmeng

…nfrastructure

### What type of PR is this?
_(/feature/)_

### What this PR does / Why we need it?
With the new OCM side change, the cluster naming policy will be changed, the cluster name may not be the same as the dns name for now.
Update the prometheus remote write to match the same value as the internal api endpoint

### Which Jira/Github issue(s) does this PR fix?

_Resolves #OSD-21606_

### Special notes for your reviewer

### Pre-checks (if applicable)

- [ ] Validated the changes in a hosted cluster
- [ ] Included documentation changes with PR

2024-03-19 08:41 UTC, supreeth7 requested changes
The non-uwm config needs to be modified as well.

Ref: https://github.com/openshift/hypershift-dataplane-metrics-forwarder/pull/54/files#diff-9e00c525fa5975e0d9cc35010664db0aada68d238e2c86ce7d64d8a4d24d48acR315

2024-03-19 08:45 UTC, bmeng commented on hack/templates/00-hypershift-dataplane-metrics-forwarder.SelectorSyncSet.yaml.tmpl
> +                                  - url: {{ ( trimAll ":443" (( lookup "config.openshift.io/v1" "Infrastructure" "default" "cluster").status.apiServerInternalURI )) | replace "api" "metrics-forwarder
nice catch..
yeah, I think that would be the issue, will fix the replace string

2024-03-19 09:16 UTC, machi1990 commented on hack/templates/00-hypershift-dataplane-metrics-forwarder.SelectorSyncSet.yaml.tmpl
> +                                  - url: {{ ( trimAll ":443" (( lookup "config.openshift.io/v1" "Infrastructure" "default" "cluster").status.apiServerInternalURI )) | replace "api" "metrics-forwarder
Thanks.

2024-03-20 04:53 UTC, supreeth7 approved these changes
/lgtm

2024-03-20 04:56 UTC, merged